# Generated by Django 6.0.5 on 2026-05-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description_ru', models.TextField(verbose_name='description in Russian')),
                ('description_en', models.TextField(verbose_name='description in English')),
                ('icon_classes', models.CharField(default='fa fa-regular fa-edit', help_text='Font Awesome classes, for example: fa fa-brands fa-android', max_length=120)),
                ('anchor', models.SlugField(help_text='HTML anchor used in links, for example: models-database-skill', max_length=80, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
